// <auto-generated />
using System;
using AppMovie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppMovie.Migrations
{
    [DbContext(typeof(AppmovieContext))]
    [Migration("20260413093440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AppMovie.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(888),
                            Description = "Un voleur qui s'infiltre dans les rêves des gens pour extraire des informations précieuses se voit offrir une chance de retrouver sa vie passée en échange d'une tâche apparemment impossible.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Genre = "Science-Fiction",
                            Language = "Anglais",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                            Price = 9.99m,
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/embed/YoHD9XEInc0"
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(925),
                            Description = "Une équipe d'explorateurs voyage à travers un trou de ver dans l'espace dans une tentative pour assurer la survie de l'humanité.",
                            Director = "Christopher Nolan",
                            Duration = 169,
                            Genre = "Science-Fiction",
                            Language = "Anglais",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lZmoaApkNFVb.jpg",
                            Price = 9.99m,
                            Rating = 8.5999999999999996,
                            ReleaseDate = new DateTime(2014, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar",
                            TrailerUrl = "https://www.youtube.com/embed/zSWdZVtXT7E"
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(930),
                            Description = "Batman élève sa guerre contre le crime à un nouveau niveau alors qu'il cherche à démanteler le crime organisé à Gotham.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Genre = "Action",
                            Language = "Anglais",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Price = 8.99m,
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/EXeTwQWrcwY"
                        },
                        new
                        {
                            Id = 4,
                            Cast = "John Travolta, Uma Thurman, Samuel L. Jackson",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(934),
                            Description = "Les vies de deux tueurs à gages, d'un boxeur, d'un gangster et de sa femme, et d'une paire de bandits se croisent dans quatre histoires de violence et de rédemption.",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Genre = "Crime",
                            Language = "Anglais",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
                            Price = 7.99m,
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction",
                            TrailerUrl = "https://www.youtube.com/embed/s7EdQ4FqbhY"
                        },
                        new
                        {
                            Id = 5,
                            Cast = "Sam Worthington, Zoe Saldana, Sigourney Weaver",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(938),
                            Description = "Un marine paraplégique est envoyé sur la lune Pandora en mission, mais il se retrouve déchiré entre les ordres de sa mission et la protection du monde qu'il commence à aimer.",
                            Director = "James Cameron",
                            Duration = 162,
                            Genre = "Science-Fiction",
                            Language = "Anglais",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
                            Price = 10.99m,
                            Rating = 7.7999999999999998,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar",
                            TrailerUrl = "https://www.youtube.com/embed/5PSNL1qE6VY"
                        },
                        new
                        {
                            Id = 6,
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            CreatedAt = new DateTime(2026, 4, 13, 9, 34, 40, 67, DateTimeKind.Utc).AddTicks(942),
                            Description = "La famille pauvre de Ki-taek s'intéresse à la riche famille Park et commence à s'infiltrer dans leur ménage en se faisant passer pour des travailleurs non liés.",
                            Director = "Bong Joon-ho",
                            Duration = 132,
                            Genre = "Thriller",
                            Language = "Coréen",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            Price = 9.99m,
                            Rating = 8.5,
                            ReleaseDate = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite",
                            TrailerUrl = "https://www.youtube.com/embed/5xH0HfJHsaY"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
